Repository Lucash2022/BookFlix-Backend, pull requests merged in 2023-07, with the labels that each got.

#25 Setup Project
  README.md
Labels: front vs back end

#28 Reservation
  Gemfile.lock
  app/controllers/api/v1/locations_controller.rb
  app/controllers/api/v1/reservations_controller.rb
  app/models/reservation.rb
  db/schema.rb
  db/seeds.rb
Labels: backend

#29 Write unit tests for reservation
  Gemfile.lock
  app/models/location.rb
  app/models/movie.rb
  db/schema.rb
  spec/models/location_spec.rb
  spec/models/movie_spec.rb
  spec/models/reservation_spec.rb
  spec/models/service_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
Labels: backend, testing

#30 Write unit tests for user authentication
  app/views/api/v1/users/_api_v1_user.json.jbuilder
  app/views/api/v1/users/index.json.jbuilder
  app/views/api/v1/users/show.json.jbuilder
  config/initializers/devise.rb
  spec/requests/api/login_spec.rb
  spec/requests/api/v1/locations_spec.rb
  spec/requests/api/v1/reservations_spec.rb
  spec/requests/api/v1/services_spec.rb
  spec/requests/api/v1/users_spec.rb
  spec/swagger_helper.rb
  spec/user_spec.rb
Labels: backend, testing
